const routeTitles = [
    { path: '/', title: 'Discover New Horizons | Unforgettable Experiences Await You' },
    { path: '/register', title: 'Register | Join us for an Amazing Experience' },
    { path: '/login', title: 'Login | Access Your Account' },
    { path: '/about', title: 'About Us | Learn More About Our Journey' },
    { path: '/contact', title: 'Contact Us | Get in Touch with Us' },
    { path: '/pooja-list', title: '50+ Poojas - Book Best Experience Priests Online for Your Spiritual Pooja' },
    { path: '/place-list', title: '50+ Places - Book Best Experienced Guiders Online' },
    { path: '/priest-list', title: '70+ Priests - Book Best Experienced Priests Online for Your Spiritual Pooja' },
    { path: '/guider-list', title: '70+ Guiders - Book Best Experienced Guiders Online' },
    { path: '/places', title: '50+ Places - Explore Must-Visit Destinations and Enjoy Wonderful Experiences' },
    { path: '/hotels', title: '70+ Hotels - Book Best Experience Hotels Online | Best Budget Hotels' },
    { path: '/testimonial', title: 'Testimonials | See What Our Happy Clients Say' },
    { path: '/car', title: 'Online Car Bookings | Best Budget Journey for You' },
    { path: '/boat', title: 'Online Boat Bookings | Spiritual Ganga Aarti & Best Budget Rides' },
    { path: '/reset-password/:resetToken', title: 'Reset Password | Secure Your Account' },
    { path: '/hotel/:id', title: 'Hotel Details | Discover Amenities & Reviews' },
    { path: '/profile/:fullName', title: 'Profile | Manage Your Account' },
    { path: '/car-book/:id', title: 'Book Car | Reserve Your Preferred Vehicle' },
    { path: '/hotel-book/hotel/:id/room/:roomId', title: 'Book Hotel Room | Select the Best Rooms with Amenities' },
    { path: '/boat-book/:id', title: 'Book Boat | Secure Your Spiritual Ride' },
    { path: '/priest-book/:id', title: 'Book Priest | Reserve an Experienced Priest for Your Pooja' },
    { path: '/guider-book/:id', title: 'Book Guider | Find the Best Guider for Your Journey' },
    { path: '/order/car-book/:id', title: 'Past Car Bookings | Review Your Journey History' },
    { path: '/order/boat-book/:id', title: 'Past Boat Bookings | Review Your Spiritual Ride History' },
    { path: '/order/priest-book/:id', title: 'Past Priest Bookings | Review Your Spiritual Pooja History' },
    { path: '/order/guider-book/:id', title: 'Past Guider Bookings | Review Your Travel History' },
    { path: '/order/hotel-book/:id', title: 'Past Hotel Bookings | Review Your Stay History' },
    { path: '/car-book-detail/:id', title: 'Car Booking Detail | Complete Booking Information' },
    { path: '/boat-book-detail/:id', title: 'Boat Booking Detail | Complete Booking Information' },
    { path: '/priest-book-detail/:id', title: 'Priest Booking Detail | Complete Booking Information' },
    { path: '/guider-book-detail/:id', title: 'Guider Booking Detail | Complete Booking Information' },
    { path: '/hotel-book-detail/:id', title: 'Hotel Booking Detail | Complete Booking Information' },
];

export default routeTitles;
